# Generated by Django 3.2 on 2025-01-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomato_image', models.ImageField(upload_to='tomato_images/')),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('soil_type', models.CharField(max_length=255)),
                ('diagnosis_result', models.TextField()),
                ('diagnosis_class', models.IntegerField()),
                ('diagnosis_confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
