# Generated by Django 3.2 on 2025-02-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasediagnosis',
            name='irrigation_frequency',
            field=models.CharField(choices=[('irrégulière', 'Irrégulière'), ('régulière', 'Régulière')], default='irrégulière', max_length=100),
        ),
        migrations.AddField(
            model_name='diseasediagnosis',
            name='plantation_density',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('élevée', 'Élevée')], default='moyenne', max_length=10),
        ),
        migrations.AddField(
            model_name='diseasediagnosis',
            name='shading_level',
            field=models.CharField(choices=[('faible', 'Faible'), ('modéré', 'Modéré'), ('élevé', 'Élevé')], default='modéré', max_length=10),
        ),
        migrations.AlterField(
            model_name='diseasediagnosis',
            name='soil_type',
            field=models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux')], default='argileux', max_length=10),
        ),
    ]
